package com.rubicon.rms.admin;

import com.rubicon.rms.orders.BillManagement;
import com.rubicon.rms.orders.OrderDetails;
import com.rubicon.rms.orders.GenerateReceipt;

import javax.swing.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

/**
 *
 * @author P Sreeja-VJIT
 */
public class OrderOperation extends javax.swing.JFrame {
    private OrderDetails o;
    private GenerateReceipt r;
    private String srcName;
    private String modName;
    private String modPrice;
    private String ModQuantity;
    private int pass;
    protected BillManagement b;
    private PrintWriter pw;
    /**
     * Creates new form OrderOperation
     */
    public OrderOperation() throws IOException {
        initComponents();
        performFileRelatedTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JTextArea();
        menuPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        addMenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addItem = new javax.swing.JButton();
        modText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        receiptArea = new javax.swing.JTextArea();
        itemNameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        totalPriceField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        priceReceiptLabel = new javax.swing.JLabel();
        quantReceiptLabel = new javax.swing.JLabel();
        nameReceiptLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menu.setEditable(false);
        menu.setBackground(new java.awt.Color(204, 204, 204));
        menu.setColumns(20);
        menu.setRows(5);
        jScrollPane1.setViewportView(menu);

        menuPanel.setBackground(new java.awt.Color(153, 153, 153));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        billButton.setText("Bill");
        billButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    billButtonActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        orderButton.setText("OrderDetails");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    orderButtonActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    viewButtonActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        addMenuPanel.setBackground(new java.awt.Color(102, 102, 102));
        addMenuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Which ID Item You want?");

        jLabel4.setText("Enter  Quantity");

        addItem.setText("New Item");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addMenuPanelLayout = new javax.swing.GroupLayout(addMenuPanel);
        addMenuPanel.setLayout(addMenuPanelLayout);
        addMenuPanelLayout.setHorizontalGroup(
            addMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMenuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(addMenuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)))
                .addGroup(addMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(modText))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addItem)
                .addContainerGap())
        );
        addMenuPanelLayout.setVerticalGroup(
            addMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMenuPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(addMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(modText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addItem)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewButton)
                .addGap(18, 18, 18)
                .addComponent(orderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(billButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(108, 108, 108))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(addMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(addMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(orderButton)
                    .addComponent(billButton)
                    .addComponent(backButton))
                .addGap(23, 23, 23))
        );

        receiptArea.setBackground(new java.awt.Color(204, 204, 204));
        receiptArea.setColumns(20);
        receiptArea.setRows(5);
        jScrollPane2.setViewportView(receiptArea);

        itemNameLabel.setForeground(new java.awt.Color(153, 153, 153));
        itemNameLabel.setText("Name");

        priceLabel.setForeground(new java.awt.Color(153, 153, 153));
        priceLabel.setText("Price");

        quantityLabel.setForeground(new java.awt.Color(153, 153, 153));
        quantityLabel.setText("Quantity");

        totalPriceField.setEditable(false);
        totalPriceField.setBackground(new java.awt.Color(153, 153, 153));

        idLabel.setForeground(new java.awt.Color(153, 153, 153));
        idLabel.setText("ID");

        priceReceiptLabel.setForeground(new java.awt.Color(153, 153, 153));
        priceReceiptLabel.setText("Price");

        quantReceiptLabel.setForeground(new java.awt.Color(153, 153, 153));
        quantReceiptLabel.setText("Quantity");

        nameReceiptLabel.setForeground(new java.awt.Color(153, 153, 153));
        nameReceiptLabel.setText("Name");

        totalPriceLabel.setForeground(new java.awt.Color(153, 153, 153));
        totalPriceLabel.setText("Total Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(itemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(priceLabel)
                                .addGap(48, 48, 48)
                                .addComponent(quantityLabel))
                            .addComponent(idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(nameReceiptLabel)
                        .addGap(18, 18, 18)
                        .addComponent(quantReceiptLabel)
                        .addGap(32, 32, 32)
                        .addComponent(priceReceiptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(totalPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalPriceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantReceiptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(priceReceiptLabel)
                                .addComponent(nameReceiptLabel))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(itemNameLabel)
                                .addComponent(priceLabel)
                                .addComponent(quantityLabel)
                                .addComponent(idLabel)))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalPriceLabel)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void performFileRelatedTask() throws IOException {
        o = new OrderDetails();

    }

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        try {
            o = new OrderDetails();
        } catch (IOException e) {
            e.printStackTrace();
        }
        menu.setText(o.getFullNames().toString());

    }//GEN-LAST:event_viewButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_orderButtonActionPerformed

        // o.delete();
        BillManagement b = new BillManagement();
        this.dispose();
        b.setVisible(true);

    }//GEN-LAST:event_orderButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        RestaurantManagement im = new RestaurantManagement();
        im.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_billButtonActionPerformed
        // TODO add your handling code here:

        b= new BillManagement();
        b.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_billButtonActionPerformed

    public void receiptArea(){
        String n,q;
        try {
            Scanner sc= new Scanner(new FileInputStream("temp.txt"));
            while(sc.hasNextLine()){
                n=sc.nextLine();
                q =sc.nextLine();
                // setSrchName(n);
                // setQuantity(quantity);
                receiptArea.setText(n+"\t"+ q+"\n");
            }
            System.out.println("End of reading temp file");
            sc.close();
        } catch (Exception ignored) {
        }
    }
    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        // TODO add your handling code here:
        srcName=modText.getText(); //ID
        // o.setSrchName(srcName);
        ModQuantity=mQuantity.getText(); // Quantity
        //o.setQuantity(ModQuantity);
        if(Integer.decode(ModQuantity)>o.checkQuantity(Integer.decode(srcName))){

            JOptionPane.showMessageDialog(this, "Sorry , This item is not in stock");
            mQuantity.setText("");

        } else {
            pass =Integer.decode(ModQuantity);
            o.temp(Integer.decode(srcName),pass);
            modText.setText("");

            mQuantity.setText("");
            System.out.println("will be modified "+srcName);
            System.out.println("will be modified "+pass);

            r = new GenerateReceipt();
            receiptArea.setText(r.getFullNames().toString());
            totalPriceField.setText("Total price : "+ r.getSum());
            try {
                pw = new PrintWriter(new FileOutputStream("Order.csv",true));
                pw.print(r.getName()+",");
                pw.print(r.getQuantity()+",");
                pw.print(r.getMulti()+",");
                pw.print("\n");
                pw.close();
            } catch (Exception ignored) {

            }
        }//GEN-LAST:event_addItemActionPerformed
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JPanel addMenuPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton billButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mQuantity;
    private javax.swing.JTextArea menu;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField modText;
    private javax.swing.JLabel nameReceiptLabel;
    private javax.swing.JButton orderButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceReceiptLabel;
    private javax.swing.JLabel quantReceiptLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextArea receiptArea;
    private javax.swing.JTextField totalPriceField;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}



